// <auto-generated />
using System;
using AspLab06Final.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspLab06Final.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AspLab06Final.Mvc.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AspLab06Final.Mvc.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Result");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("AspLab06Final.Mvc.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("BookCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinStock")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookCode")
                        .IsUnique();

                    b.HasIndex("GenreId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Stephen R. Covey",
                            BookCode = "BK-SKL-101",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 1,
                            IsDeleted = false,
                            MinStock = 5,
                            Price = 145000m,
                            Publisher = "NXB Trẻ",
                            Quantity = 18,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 1 },
                            Title = "7 Thói Quen Hiệu Quả"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Charles Duhigg",
                            BookCode = "BK-SKL-102",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 1,
                            IsDeleted = false,
                            MinStock = 5,
                            Price = 132000m,
                            Publisher = "NXB Lao Động",
                            Quantity = 6,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 2 },
                            Title = "Sức Mạnh Của Thói Quen"
                        },
                        new
                        {
                            Id = 3,
                            Author = "James Clear",
                            BookCode = "BK-SKL-103",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 1,
                            IsDeleted = false,
                            MinStock = 5,
                            Price = 168000m,
                            Publisher = "NXB Thế Giới",
                            Quantity = 12,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 3 },
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Ichiro Kishimi",
                            BookCode = "BK-SKL-104",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 1,
                            IsDeleted = false,
                            MinStock = 5,
                            Price = 98000m,
                            Publisher = "NXB Lao Động",
                            Quantity = 4,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 4 },
                            Title = "Dám Bị Ghét"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Hector Malot",
                            BookCode = "BK-NOV-101",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 2,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 89000m,
                            Publisher = "NXB Văn Học",
                            Quantity = 15,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 5 },
                            Title = "Không Gia Đình"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Haruki Murakami",
                            BookCode = "BK-NOV-102",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 2,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 125000m,
                            Publisher = "NXB Hội Nhà Văn",
                            Quantity = 7,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 6 },
                            Title = "Rừng Na Uy"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Jane Austen",
                            BookCode = "BK-NOV-103",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 2,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 119000m,
                            Publisher = "NXB Văn Học",
                            Quantity = 9,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 7 },
                            Title = "Kiêu Hãnh Và Định Kiến"
                        },
                        new
                        {
                            Id = 8,
                            Author = "Ray Bradbury",
                            BookCode = "BK-NOV-104",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 2,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 112000m,
                            Publisher = "NXB Thế Giới",
                            Quantity = 5,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 8 },
                            Title = "451 Độ F"
                        },
                        new
                        {
                            Id = 9,
                            Author = "Carl Sagan",
                            BookCode = "BK-SCI-101",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 3,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 178000m,
                            Publisher = "NXB Khoa Học",
                            Quantity = 8,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 9 },
                            Title = "Cosmos"
                        },
                        new
                        {
                            Id = 10,
                            Author = "Richard Dawkins",
                            BookCode = "BK-SCI-102",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 3,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 165000m,
                            Publisher = "NXB Khoa Học",
                            Quantity = 3,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 10 },
                            Title = "The Selfish Gene"
                        },
                        new
                        {
                            Id = 11,
                            Author = "Stephen Hawking",
                            BookCode = "BK-SCI-103",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 3,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 156000m,
                            Publisher = "NXB Trẻ",
                            Quantity = 2,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 11 },
                            Title = "Brief Answers to the Big Questions"
                        },
                        new
                        {
                            Id = 12,
                            Author = "Martin Fowler",
                            BookCode = "BK-TECH-101",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 4,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 245000m,
                            Publisher = "NXB Lao Động",
                            Quantity = 6,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 12 },
                            Title = "Refactoring"
                        },
                        new
                        {
                            Id = 13,
                            Author = "Erich Gamma",
                            BookCode = "BK-TECH-102",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 4,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 265000m,
                            Publisher = "NXB Lao Động",
                            Quantity = 4,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 13 },
                            Title = "Design Patterns"
                        },
                        new
                        {
                            Id = 14,
                            Author = "Eric Evans",
                            BookCode = "BK-TECH-103",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 4,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 285000m,
                            Publisher = "NXB Công Nghệ",
                            Quantity = 2,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 14 },
                            Title = "Domain-Driven Design"
                        },
                        new
                        {
                            Id = 15,
                            Author = "Steve McConnell",
                            BookCode = "BK-TECH-104",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GenreId = 4,
                            IsDeleted = false,
                            MinStock = 3,
                            Price = 238000m,
                            Publisher = "NXB Công Nghệ",
                            Quantity = 10,
                            RowVersion = new byte[] { 0, 0, 0, 0, 0, 0, 0, 15 },
                            Title = "Code Complete"
                        });
                });

            modelBuilder.Entity("AspLab06Final.Mvc.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kỹ năng sống"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tiểu thuyết"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khoa học"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Công nghệ"
                        });
                });

            modelBuilder.Entity("AspLab06Final.Mvc.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SaleCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SaleCode")
                        .IsUnique();

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("AspLab06Final.Mvc.Models.SaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookTitleSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleItems", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AspLab06Final.Mvc.Models.Book", b =>
                {
                    b.HasOne("AspLab06Final.Mvc.Models.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AspLab06Final.Mvc.Models.SaleItem", b =>
                {
                    b.HasOne("AspLab06Final.Mvc.Models.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AspLab06Final.Mvc.Models.Sale", "Sale")
                        .WithMany("Items")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AspLab06Final.Mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AspLab06Final.Mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspLab06Final.Mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AspLab06Final.Mvc.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspLab06Final.Mvc.Models.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("AspLab06Final.Mvc.Models.Sale", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
